var ResourcesModelTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-sm-8">',
                    '<h4>Resource information</h4>',
                '</div>',
                '<div class="col-sm-4">',
                    '<button class="btn btn-success pull-right edit">',
                        '<i class="glyphicon glyphicon-edit"></i> Edit',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
            '<div class="panel-body">',
                '<div class="row">',
                    '<div class="col-md-9">',
                        '<div class="form-group">',
                            '<label>Name :</label></span>',
                            '<p class="grey" name="name"><%= name %></p>',
                         '</div>',
                         '<div class="form-group">',
                            '<label>Type :</label>',
                            '<p class="grey" name="type"><%= type %></p>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="row">',
                    '<div class="col-md-12">',
                        '<button type="button" class="btn btn-warning pull-left cancel">',
                            '<i class="glyphicon glyphicon-arrow-left"></i> Back',
                        '</button>',
                        '<button type="button" class="btn btn-danger pull-right delete">',
                            '<i class="glyphicon glyphicon-remove"></i> Delete',
                        '</button>',
                    '</div>',
                '</div>',
            '</div>',
    '</div>'
].join(''));