templates.monthTpl = _.template([
    '<% function getDay(date) { %>',
    '  <% var day = date.getDay(); %>',
    '  <% if (day == 0) day = 7; %>',
    '  <% return day - 1; %>',
    '<% } %>',
    '<table class="<%= mon %>">',
    '<tr class="monthHeader"> <td align="center" colspan="7"> <%= monthName %> </td> </tr>',
    '<tr><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th><th>Sun</th></tr>',
    '<tr class="days">',
      '<% for (var i = 0; i < getDay(date); i++) { %>',
        '<td></td>',
      '<% } %>',
      '<% while (date.getMonth() == mon) { %>',
        '<td> <%= date.getDate() %> </td>',
        '<% if (getDay(date) % 7 == 6) { %>',
           '</tr><tr class="days <%= date.getDate() + 1 %>">',
        '<% } %>',
        '<% date.setDate(date.getDate() + 1); %>',
      '<% } %>',
      '<% if (getDay(date) != 0) { %>',
        '<% for (var i = getDay(date); i < 7; i++) { %>',
            '<td></td>',
        '<% } %>',
      '<% } %>',
      '</tr></table>'
].join(''));