templates.weekTpl = _.template([
            '  	<tr class="daysName">',
            '		<td>',
            '		</td>',
            '		<td>',
            '			Monday',
            '		</td>',
            '		<td>',
            '			Tuesday',
            '		</td>',
            '		<td>',
            '			Wednesday',
            '		</td>',
            '		<td>',
            '			Thursday',
            '		</td>',
            '		<td>',
            '			Friday',
            '		</td>',
            '	</tr>',
            '	<tr class="daysDate">',
            '		<td></td>',
            '		<td>',
            '			<%= new Date(week.startDate).getDate() %>.<%= new Date(week.startDate).getMonth() + 1 %>',
            '		</td>',
            '		<td>',
            '			<%= new Date(week.startDate).getDate() +1 %>.<%= new Date(week.startDate).getMonth() + 1 %>',
            '		</td>',
            '		<td>',
            '			<%= new Date(week.startDate).getDate() + 2 %>.<%= new Date(week.startDate).getMonth() + 1 %>',
            '		</td>',
            '		<td>',
            '			<%= new Date(week.startDate).getDate() + 3 %>.<%= new Date(week.startDate).getMonth() + 1 %>',
            '		</td>',
            '		<td>',
            '			<%= new Date(week.startDate).getDate() + 4 %>.<%= new Date(week.startDate).getMonth() + 1 %>',
            '		</td>',
            '	</tr>',
            '<% _.each(templates.timelines, function (value) { %>',
            '	<tr  timeline = "<%= value %>">',
            '		<td>',
            '			<%= value %>',
            '		</td>',
            '		<td day= "<%= 1 %>">',
            '       <% _.each(resources, function (resource, day) { %>',
            '           <% if (day == 1) { %>',
            '               <% _.each(resource, function (r, time) { %>',
            '                   <% if (time === value) { %>',
            '                       <% _.each(events, function (event) { %>',
            '                           <% if (event.id == r) { %>',
            '                               <%= event.name %>',
            '                           <% } %>',
            '                       <% }); %>',
            '                   <% } %>',
            '               <% }); %>',
            '           <% } %>',
            '       <% }); %>',
            '		</td>',
            '		<td day= "<%= 2 %>">',
            '       <% _.each(resources, function (resource, day) { %>',
            '           <% if (day == 2) { %>',
            '               <% _.each(resource, function (r, time) { %>',
            '                   <% if (time === value) { %>',
            '                       <% _.each(events, function (event) { %>',
            '                           <% if (event.id == r) { %>',
            '                               <%= event.name %>',
            '                           <% } %>',
            '                       <% }); %>',
            '                   <% } %>',
            '               <% }); %>',
            '           <% } %>',
            '       <% }); %>',
            '		</td>',
            '		<td day= "<%= 3 %>">',
            '       <% _.each(resources, function (resource, day) { %>',
            '           <% if (day == 3) { %>',
            '               <% _.each(resource, function (r, time) { %>',
            '                   <% if (time === value) { %>',
            '                       <% _.each(events, function (event) { %>',
            '                           <% if (event.id == r) { %>',
            '                               <%= event.name %>',
            '                           <% } %>',
            '                       <% }); %>',
            '                   <% } %>',
            '               <% }); %>',
            '           <% } %>',
            '       <% }); %>',
            '		</td>',
            '		<td day= "<%= 4 %>">',
            '       <% _.each(resources, function (resource, day) { %>',
            '           <% if (day == 4) { %>',
            '               <% _.each(resource, function (r, time) { %>',
            '                   <% if (time === value) { %>',
            '                       <% _.each(events, function (event) { %>',
            '                           <% if (event.id == r) { %>',
            '                               <%= event.name %>',
            '                           <% } %>',
            '                       <% }); %>',
            '                   <% } %>',
            '               <% }); %>',
            '           <% } %>',
            '       <% }); %>',
            '		</td>',
            '		<td day= "<%= 5 %>">',
            '       <% _.each(resources, function (resource, day) { %>',
            '           <% if (day == 5) { %>',
            '               <% _.each(resource, function (r, time) { %>',
            '                   <% if (time === value) { %>',
            '                       <% _.each(events, function (event) { %>',
            '                           <% if (event.id == r) { %>',
            '                               <%= event.name %>',
            '                           <% } %>',
            '                       <% }); %>',
            '                   <% } %>',
            '               <% }); %>',
            '           <% } %>',
            '       <% }); %>',
            '		</td>',
            '	</tr>',
            '<% }); %>'
].join(''));