
templates.editEventTpl = _.template([
   '<div id="evetModal" class="modal fade" tabindex="-1" role="dialog" data-backdrop="static">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
				'<div class="modal-header">',
				    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
					'<h4 class="modal-title"><%= (name === "")? "Create event": "Edit event" %></h4>',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="form-group" class="col-xs-4">',
                        ' <label for="name">Name</label>',
                        '<input type="text" class="name form-control editName" value="<%= name %>" placeholder="type name">',
                    '</div>',
                    '<div class="form-group"  data-name="type">',
                        '<label>Type:</label>',
                        '<select size="1" class="type form-control listbox editType">',
                            '<option></option>',
                            '<%_.each(eventTypes, function (type) {%>',
                                '<% if (type.id === typeId) { %>',
                                    '<option selected value="<%= type.id %>">',
                                        '<%= type.name %>',
                                    '</option>',
                                '<% } else {%>',
                                    '<option value="<%= type.id %>">',
                                        '<%= type.name %>',
                                    '</option>',
                                '<% }%>',
                            '<%})%>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6">',
                            '<h4>Resources in</h4>',
                            '<ul class="resource-field list-group">',
                                '<% _.each(resourcesList, function (resourceItem) { %>',
                                    '<li idValue = "<%= resourceItem.get(\'id\')%>"  class="resource list-group-item" >',
                                        '<%= resourceItem.get(\'name\')%>',
                                    '</li>',
                                '<% }); %>',
                            '</ul>',
                        '</div>',
                        '<div class="col-md-6 resources-list">',
                            '<h4>Resources free</h4>',
                        '</div>',
                    '</div>',
                '</div>',
				'<div class="modal-footer">',
				    '<button id="save" type="button" class="btn btn-info save pull-right">',
                        '<i class="glyphicon glyphicon-floppy-saved"></i> Save',
                    '</button>',
                    '<button type="button" class="btn btn-default cancel pull-left" data-dismiss="modal" aria-label="Close">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Back',
                    '</button>',
				    '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));