
templates.editEventTpl = _.template([
    '<div class="modal-backdrop fade in" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true"></div>',
        '<div class="modal-dialog modal-md">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                     '<h4 class="modal-title">Edit event</h4>',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="form-group" class="col-xs-4">',
                        ' <label for="name">Name</label>',
                        '<input type="text" class="name form-control editName" value="<%= name %>" placeholder="type name">',
                    '</div>',
                    '<div class="form-group"  data-name="type">',
                        '<label>Type:</label>',
                        '<select size="1" class="type form-control listbox editType">',
                            '<%_.each(eventTypes, function (type) {%>',
                                '<% if (type.id === typeId) { %>',
                                    '<option selected value="<%= type.id %>">',
                                        '<%= type.name %>',
                                    '</option>',
                                '<% } %>',
                                    '<option value="<%= type.id %>">',
                                        '<%= type.name %>',
                                    '</option>',
                            '<%})%>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6">',
                            '<h4>Resources in</h4>',
                            '<ul class="resource-field list-group">',
                                '<% _.each(resourcesList, function (resourceItem) { %>',
                                    '<li idValue = "<%= resourceItem.get(\'id\')%>"  class="resource list-group-item" >',
                                        '<%= resourceItem.get(\'name\')%>',
                                    '</li>',
                                '<% }); %>',
                            '</ul>',
                        '</div>',
                        '<div class="col-md-6 resources-list">',
                            '<h4>Resources free</h4>',
                        '</div>',
                    '</div>',
                    '<button type="button" class="btn btn-info save pull-right">',
                        '<i class="glyphicon glyphicon-floppy-saved"></i> Save',
                    '</button>',
                    '<button type="button" class="btn btn-default cancel pull-left">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Back',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'

].join(''));