
var editEventTpl = _.template([
    '<div class="modal-backdrop fade in"></div>',
        '<div class="modal-dialog modal-md">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                     '<h4 class="modal-title">Edit event</h4>',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="form-group" class="col-xs-4">',
                        ' <label for="name">Name</label>',
                        '<input type="text" id="name" name="name" class="form-control" placeholder="type name">',
                    '</div>',
                    '<div class="form-group"  data-name="type">',
                        '<label>Type:</label>',
                        '<select size="3" multiple name="type" class="form-control listbox">',
                            '<option value="lecture">lecture</option>',
                            '<option value="scrum" >scrum</option>',
                            '<option value="practice" >practice </option>',
                            '<option value="report">weekly report</option>',
                        '</select>',
                    '</div>',
                    '<div class="form-group">',
                        '<select size="5" multiple name="resources" class="form-control resource-field">',
                            '<% _.each(resourcesList, function (resourceItem) { %>',
                                '<option class="option" value="<%= resourceItem.get(\'id\')%>" >',
                                '<%= resourceItem.get(\'name\')%>',
                                '</option>',
                            '<% }); %>',
                        '</select>',
                    '</div>',
                    '<div class="form-group resources-list">',
                    '</div>',
                    '<button type="button" class="btn btn-info save pull-right">',
                        '<i class="glyphicon glyphicon-floppy-saved"></i> Save',
                    '</button>',
                    '<button type="button" class="btn btn-default cancel pull-left">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Back',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'

].join(''));