templates.daysRowTpl = _.template([
'	<tr>',
'		<td class="cell" chooseWeek = "">',
'		</td>',
'		<% dayNumber = 1%>',
'		<td class="cell" chooseDay = <%= dayNumber++%>>',
'			Monday',
'		</td>',
'		<td class="cell" chooseDay = <%= dayNumber++%>>',
'			Tuesday',
'		</td>',
'		<td class="cell" chooseDay = <%= dayNumber++%>>',
'			Wednesday',
'		</td>',
'		<td class="cell" chooseDay = <%= dayNumber++%>>',
'			Thursday',
'		</td>',
'		<td class="cell" chooseDay = <%= dayNumber++%>>',
'			Friday',
'		</td>',
'	</tr>',
'	<tr>',
'		<td class="cell" chooseWeek = ""></td>',
'		<td class="cell">',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'	</tr>'].join(''));