templates.createAccountTpl = _.template([
'<div id="accountModal" class="modal fade" tabindex="-1" role="dialog" data-backdrop="static">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
				'<div class="modal-header">',
				    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
					 '<h4 class="modal-title"><%= (fullName === "")? "Create account": "Edit account" %></h4>',
                '</div>',
                 '<div class="modal-body clearfix">',
                    '<div class="accountForm">',
                    '<div class="form-group" class="col-xs-4">',
                        '<label for="InputFullName">Enter FullName</label>',
                        '<input type="text" class="form-control" value="<%= fullName %>" name="fullName" id="InputFullName" placeholder="Enter FullName">',
                    '</div>',
                    '<div class="form-group" class="col-xs-4">',
                        '<label for="InputLogin">Enter Login</label>',
                        '<input type="text" class="form-control" value="<%= login %>" name="login" id="InputLogin" placeholder="Enter Login">',
                    '</div>',
                    '<div class="form-group" class="col-xs-4">',
                         '<label for="InputPassword">Enter Password</label>',
                        '<input type="text" class="form-control" value="<%= password %>" name="password" id="InputPassword" placeholder="Enter Password">',
                    '</div>',
                    '<div class="form-group">',
                        '<label for="locationCity">Select City</label>',
                        '<select class="form-control listbox" name="locationCity">',
                            '<% if (city) { %>',
                                '<option selected value="<%= city.id %>">',
                                    '<%= city.get("name") %>',
                                '</option>',
                            '<% } else {%>',
                            '<option value="" default disabled selected>select city</option>',
                            '<% }%>',                            
                           '<% _.each(locationCity, function (city) {%>',
                                '<option value="<%= city.id %>">',
                                    '<%= city.name %>',
                                '</option>',
                        '<% }) %>',
                        '</select>',
                    '</div>',
                    '<div class="form-group">',
                        '<label for="role">Select Role</label>',
                          '<select class="form-control" name="role">',
                        '<% if (role) { %>',
                            '<option value="<%= role %>"><%= role %></option>',
                            '<% if (role === "Admin") { %>',
                                '<option value="Coordinator">Coordinator</option>',
                            '<% } else {%>',
                                '<option value="Admin">Admin</option>',
                            '<% }%>',
                        '<% } else {%>',
                            '<option value="Coordinator">Coordinator</option>',
                            '<option value="Admin">Admin</option>',
                            '<% }%>',
                        '</select>',
                      '</div>',
                    '</div>',
				'<div class="modal-footer">',
				    '<button id="save" type="button" class="btn btn-info save pull-right">',
                        '<i class="glyphicon glyphicon-floppy-saved"></i> Save',
                    '</button>',
                    '<button type="button" class="btn btn-default cancel pull-left" data-dismiss="modal" aria-label="Close">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Back',
                    '</button>',
				    '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));  