templates.createAccountTpl = _.template([
        '<div class="modal-backdrop fade in"></div>',
        '<div class="modal-dialog modal-md">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                     '<h4 class="modal-title">Create/Edit account</h4>',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="form-group" class="col-xs-4">',
                        '<label for="InputFullName">Enter FullName</label>',
                        '<input type="text" class="form-control" value="<%= fullName %>" name="fullName" id="InputFullName" placeholder="Enter FullName">',
                    '</div>',
                    '<div class="form-group" class="col-xs-4">',
                        '<label for="InputLogin">Enter Login</label>',
                        '<input type="text" class="form-control" value="<%= login %>" name="login" id="InputLogin" placeholder="Enter Login">',
                    '</div>',
                    '<div class="form-group" class="col-xs-4">',
                         '<label for="InputPassword">Enter Password</label>',
                        '<input type="text" class="form-control" value="<%= password %>" name="password" id="InputPassword" placeholder="Enter Password">',
                    '</div>',
                     '<div class="form-group">',
                       '<label for="InputCountry">Select Country</label>',
                         '<select class="form-control" id="InputCountry" name="locationCountry">',
                            '<%_.each(locationCountry, function (country) {%>',
                                '<option value="<%= country.id %>">',
                                    '<%= country.name %>',
                                '</option>',
                            '<%})%>',
                        '</select>',
                    '</div>',
                    '<div class="form-group">',
                        '<label for="InputCity">Select City</label>',
                        '<select class="form-control listbox" name="locationCity" id="InputCity">',
                            '<%_.each(locationCity, function (city) {%>',
                                '<option value="<%= city.id %>">',
                                    '<%= city.name %>',
                                '</option>',
                            '<%})%>',
                        '</select>',
                    '</div>',
                    '<div class="form-group">',
                        '<label for="InputRole">Select Role</label>',
                         '<select class="form-control" id="InputRole" name="role">',
                            '<option value="Coordinator">Coordinator</option>',
                            '<option value="Admin">Admin</option>',
                        '</select>',
                    '</div>',
                    '<button type="button" class="btn btn-info save pull-right">',
                        '<i class="glyphicon glyphicon-floppy-saved"></i> Save',
                    '</button>',
                    '<button type="button" class="btn btn-default cancel pull-left">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Back',
                    '</button>',
                '</div>',
            '</div>',
        '</div>'].join(''));  