'use strict';
var loginAccountTpl = _.template([
	'<div class="top-content">',
        '<div class="inner-bg">',
            '<div class="container">',
                '<div class="row">',
                    '<div class="col-sm-6 col-sm-offset-3 form-box">',
                        '<div class="form-top">',
                            '<div class="form-top-left">',
                                '<h3>Login to Caesar or <a>Create Account</a></h3>',
                                '<p>Enter your username to log on:</p>',
                            '</div>',
                        '</div>',
                        '<div class="form-bottom">',
                            '<form role="form" action="" method="post" class="login-form">',
                                '<div class="form-group">',
                                    '<label class="sr-only" for="form-username">Username</label>',
                                    '<input type="text" name="form-username" placeholder="Username..." class="form-username form-control" id="form-username">',
                                '</div>',
                                '<button type="submit" class="btn submit">Log in</button>',
                            '</form>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'].join(''));