templates.holidaysCollectionTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-md-4 col-sm-2">',
                    '<h4>Holidays</h4>',
                '</div>',
                '<div class="btn-group col-md-5 col-sm-6" role="group">',
                    '<button type="button" class="all btn btn-default">All</button>',
                    '<button type="button" class="0 btn btn-default">Ukraine</button>',
                    '<button type="button" class="1 btn btn-default">Bulgaria</button>',
                '</div>',
                '<div class="col-md-3 col-sm-4">',
                    '<button class="btn btn-success pull-right create">',
                        '<i class="glyphicon glyphicon-plus-sign"></i> Add',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
        '<table class="table holidays-list">',
        '</table>',
    '</div>'
].join(''));