templates.preViewScheduleTpl = _.template([
    '<div class="modal-backdrop fade in"></div>',
	'<div class="modal-dialog animated slideInDown myAnimateClass">',
		'<div class="modal-content">',
			'<div class="modal-header">',
			    '<button type="button" class="close cancel"><span aria-hidden="true">&times;</span></button>',
				'<h4 class="modal-title">KL</h4>',
			'</div>',
			'<div class="modal-body clearfix">',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'<p>Результаты поиска How can I change IE8? </p>',
			'</div>',
			'<div class="modal-footer">',
				'<button id="save" type="button" class="btn btn-info save pull-right">',
					'<i class="glyphicon glyphicon-floppy-saved"></i> Save',
				'</button>',
				'<button type="button" class="btn btn-default cancel pull-left">',
					'<i class="glyphicon glyphicon-floppy-remove"></i> Back',
				'</button>',
			'</div>',
		'</div>',
	'</div>'	
].join(''));
