templates.preViewScheduleTpl = _.template([

	'<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">',
        '<div class="modal-dialog modal-lg">',
            '<div class="modal-content">',
                '<div class="modal-header">',
					'<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
					'<h4 class="modal-title" id="myModalLabel">Modal title</h4>',
				  '</div>',
				  '<div class="modal-body">',
				   '<input type="text" class="name form-control editName" value="" placeholder="type name">',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',
'<p>Результаты поискаHow can I change the width of a Bootstrap 3 modal in IE8?stackoverflow.com</p>',

			  '</div>',
			  '<div class="modal-footer">',
				'<button id="closePreViewSchedule" type="button" class="btn btn-default " data-dismiss="modal">Close</button>',
				'<button type="button" class="btn btn-primary save">Save changes</button>',
			  '</div>',
            '</div>',
        '</div>',
    '</div>'
	
	
].join(''));
