templates.scheduleConfirmTpl = _.template([
    '<div class="modal-backdrop fade in"></div>',
        '<div class="modal-dialog modal-lg">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<h4 class="modal-title"><%= message %> </h4>',
                    'What action should be provided?',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="btn-group">',
                        '<button type="button" class="btn btn-default delete">',
                            '<b><i>',
                            '<%= newEvent %>',
                            '</i></b>',
                            '<br>',
                            ' use NEW event ',
                            '<br>',
                            '<%= oldEvent %>',
                        '</button>',
                        '<button type="button" class="btn btn-default cancel">',
                            '<%= newEvent %>',
                            '<br>',
                            ' use OLD event ',
                            '<br>',
                            '<b><i>',
                            '<%= oldEvent %>',
                            '</i></b>',
                        '</button>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));