var weekTpl = [
'<h3>Scheduled event: <%= eventName %></h3>',
'<table>',
'   <thead>',
'       <tr>',
'           <th rowspan="2">days / intervals</th>',
'           <th colspan="7">Week # <%= weekNumber %></th>',
'       </tr>',
'       <tr>',
'           <% _.each(getWeekDays(weekNumber), function (date) { %>',
'               <th><%= formatDate(date) %></th>',
'           <% }) %>',
'       </tr>',
'   </thead>',
'	<tbody>',
'   	<% _.each(intervals, function (timeValue, intervalId) { %>',
'       	<tr>',
'           	<td class="intervals">',
'               	<%= timeValue %>',
'           	</td>',
'           	<% _.each(getWeekDays(weekNumber), function (date) { %>',
'               	<td data-interval="<%= intervalId %>" ',
'                   	data-day="<%= date.getDay() %>" class="grid-cell">',
//'                   	<%= intervalId + ", " + date.getDay() %>',
'               	</td>',
'           	<% }) %>',
'       	</tr>',
'   	<% }) %>',
'	</tbody>',
'</table>',
].join('\n');